USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS DEMO_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Dedicated compute warehouse for GitHub Actions CI/CD deployment runs';


CREATE DATABASE IF NOT EXISTS DEMO_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_DB.SCHEMACHANGE;


CREATE ROLE IF NOT EXISTS DEMO_ROLE;

GRANT USAGE ON WAREHOUSE DEMO_WH TO ROLE DEMO_ROLE;

GRANT USAGE, CREATE SCHEMA ON DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DEMO_DB.SCHEMACHANGE TO ROLE DEMO_ROLE;


CREATE USER IF NOT EXISTS DEMO_USER
  PASSWORD = 'DemoPassword123!'
  DEFAULT_ROLE = DEMO_ROLE
  DEFAULT_WAREHOUSE = DEMO_WH
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account user for GitHub Actions schemachange runner';

GRANT ROLE DEMO_ROLE TO USER DEMO_USER;


GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE DEMO_DB TO ROLE DEMO_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE DEMO_DB TO ROLE DEMO_ROLE;

