create OR REPLACE database DB_CITIES;

create OR REPLACE schema CITIES;
create OR REPLACE table  DB_CITIES.CITIES.CITIES_LIST (CITIES_NAME  VARCHAR);

INSERT INTO DB_CITIES.CITIES.CITIES_LIST(CITIES_NAME) VALUES ('MANCHESTER');
INSERT INTO DB_CITIES.CITIES.CITIES_LIST(CITIES_NAME) VALUES ('BRIGHTON');
INSERT INTO DB_CITIES.CITIES.CITIES_LIST(CITIES_NAME) VALUES ('LONDON');

CREATE OR REPLACE DATABASE ROLE CITIES_DB_READER;

GRANT USAGE ON SCHEMA DB_CITIES.CITIES TO DATABASE ROLE CITIES_DB_READER;
GRANT SELECT ON ALL TABLES IN DATABASE DB_CITIES TO DATABASE ROLE CITIES_DB_READER;


SHOW GRANTS TO DATABASE ROLE CITIES_DB_READER;

create role CITIES_READER;
GRANT DATABASE ROLE CITIES_DB_READER TO ROLE CITIES_READER;;
CREATE OR REPLACE USER CITIES_ANALYST 
PASSWORD='123'
must_change_password=false;

DROP USER CITIES_ANALYST; 


GRANT MODIFY,MONITOR,OPERATE,USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CITIES_READER;

GRANT ROLE CITIES_READER TO USER CITIES_ANALYST;
