-- Use SECURITYADMIN for RBAC management
USE ROLE SECURITYADMIN;

-- 1. Create Functional Role (The 'Who')
CREATE ROLE IF NOT EXISTS DATA_ANALYST_FR;

-- 2. Create Access Roles (The 'What')
CREATE ROLE IF NOT EXISTS SALES_RAW_READ_AR;
CREATE ROLE IF NOT EXISTS SALES_REPORTING_WRITE_AR;

-- 3. Build the Hierarchy
-- Link Access Roles to Functional Roles
GRANT ROLE SALES_RAW_READ_AR TO ROLE DATA_ANALYST_FR;
GRANT ROLE SALES_REPORTING_WRITE_AR TO ROLE DATA_ANALYST_FR;

-- Always roll custom roles up to SYSADMIN for visibility
GRANT ROLE DATA_ANALYST_FR TO ROLE SYSADMIN;


-- Switching to SYSADMIN to create objects
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS SALES_DB;
CREATE SCHEMA IF NOT EXISTS SALES_DB.RAW;

-- Granting privileges to the Access Roles
USE ROLE SECURITYADMIN;

-- Read Access
GRANT USAGE ON DATABASE SALES_DB TO ROLE SALES_RAW_READ_AR;
GRANT USAGE ON SCHEMA SALES_DB.RAW TO ROLE SALES_RAW_READ_AR;
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB.RAW TO ROLE SALES_RAW_READ_AR;

-- Future Grants (Critical for Architect Exam)
-- Ensures new tables automatically get these permissions
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.RAW TO ROLE SALES_RAW_READ_AR;


USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS "SACHIN" 
    PASSWORD = '123' 
    DEFAULT_ROLE = DATA_ANALYST_FR
    MUST_CHANGE_PASSWORD = TRUE;

USE ROLE SECURITYADMIN;
GRANT ROLE DATA_ANALYST_FR TO USER "SACHIN";
