

USE ROLE ACCOUNTADMIN;

-- Create Roles
CREATE OR REPLACE ROLE ANALYST_ROLE;
CREATE OR REPLACE ROLE TESTER_ROLE;
CREATE OR REPLACE ROLE DEVELOPER_ROLE;

-- Create User
CREATE OR REPLACE USER ADMIN_USER PASSWORD = '123' DEFAULT_ROLE = ANALYST_ROLE;
GRANT ROLE ANALYST_ROLE TO USER ADMIN_USER;
GRANT ROLE TESTER_ROLE TO USER ADMIN_USER;
GRANT ROLE DEVELOPER_ROLE TO USER ADMIN_USER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TESTER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEVELOPER_ROLE;

-- Create Isolated Database and Schemas
CREATE OR REPLACE DATABASE SECONDARY_DEMO;
REVOKE USAGE ON DATABASE SECONDARY_DEMO FROM ROLE PUBLIC;

CREATE OR REPLACE SCHEMA SECONDARY_DEMO.ANALYST_SCH;
CREATE OR REPLACE SCHEMA SECONDARY_DEMO.TESTER_SCH;

-- Transfer Ownership and STRIP all existing grants
GRANT OWNERSHIP ON SCHEMA SECONDARY_DEMO.ANALYST_SCH TO ROLE ANALYST_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SECONDARY_DEMO.TESTER_SCH TO ROLE TESTER_ROLE REVOKE CURRENT GRANTS;

-- Only grant the "Entry Door" to the DB
GRANT USAGE ON DATABASE SECONDARY_DEMO TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE SECONDARY_DEMO TO ROLE TESTER_ROLE;




USE ROLE ANALYST_ROLE;
CREATE OR REPLACE TABLE SECONDARY_DEMO.ANALYST_SCH.TABLE_A AS SELECT 'Analyst Data' AS COL;

USE ROLE TESTER_ROLE;
CREATE OR REPLACE TABLE SECONDARY_DEMO.TESTER_SCH.TABLE_T AS SELECT 'Tester Data' AS COL;



-- Switch to Analyst
USE ROLE ANALYST_ROLE;
USE WAREHOUSE COMPUTE_WH;

-- CRITICAL: Disable any secondary roles left over from your previous chat/session Snowflake sessions are "sticky." Because we were testing USE SECONDARY ROLES ALL in the previous turns, your worksheet was still using that setting. By adding USE SECONDARY ROLES NONE;, you force Snowflake to look only at your primary role (ANALYST_ROLE), which correctly blocks the TESTER_SCH.
USE SECONDARY ROLES NONE; 

-- TEST 1: This will now properly FAIL (The Walls are UP)
-- Error: Object 'TABLE_T' does not exist or not authorized.
SELECT * FROM SECONDARY_DEMO.TESTER_SCH.TABLE_T; 

-- TEST 2: Turn the "Union" back ON
USE SECONDARY ROLES ALL;

-- TEST 3: This will now properly SUCCEED (The Walls are bypassed by the Union)
SELECT * FROM SECONDARY_DEMO.TESTER_SCH.TABLE_T;
