CREATE DATABASE IF NOT EXISTS DBT_NATIVE_DB;
CREATE SCHEMA IF NOT EXISTS DBT_NATIVE_DB.ANALYTICS;

CREATE OR REPLACE SECRET DBT_NATIVE_DB.ANALYTICS.github_pat_secret
    TYPE = password
    USERNAME = 'JaswinderSingh41'
    PASSWORD = 'ghp_0w9gc0kXloo5qPOUPBysw1HIEpb';

CREATE OR REPLACE API INTEGRATION github_api_integration
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/JaswinderSingh41/')
    ALLOWED_AUTHENTICATION_SECRETS = (DBT_NATIVE_DB.ANALYTICS.GITHUB_PAT_SECRET)
    ENABLED = TRUE;


