CREATE OR REPLACE SCHEMA SECURITY_LAB_DB.MGD_SCH WITH MANAGED ACCESS;

GRANT USAGE ON SCHEMA SECURITY_LAB_DB.MGD_SCH TO ROLE RAM;
GRANT USAGE ON SCHEMA SECURITY_LAB_DB.MGD_SCH TO ROLE SHAM;

GRANT CREATE TABLE ON SCHEMA  SECURITY_LAB_DB.MGD_SCH TO ROLE RAM;

USE ROLE RAM;
USE WAREHOUSE LAB_WH;

CREATE OR REPLACE TABLE  SECURITY_LAB_DB.MGD_SCH.RAM_TABLE(ID INT,DATA STRING);
INSERT INTO SECURITY_LAB_DB.MGD_SCH.ram_table VALUES (1, 'mANAGED sCEHMA Schema Data');

--USE SECONDARY ROLES NONE;

SELECT * FROM SECURITY_LAB_DB.MGD_SCH.ram_table;

GRANT SELECT ON TABLE SECURITY_LAB_DB.MGD_SCH.RAM_TABLE TO ROLE SHAM;


USE ROLE ACCOUNTADMIN;
GRANT SELECT ON TABLE SECURITY_LAB_DB.MGD_SCH.RAM_TABLE TO ROLE SHAM;
USE ROLE SHAM;
SELECT * FROM SECURITY_LAB_DB.MGD_SCH.RAM_TABLE;



show tables;


select * from data_tbl;
