USE ROLE USERADMIN;

CREATE OR REPLACE ROLE RAM;
CREATE OR REPLACE ROLE SHAM;

BEGIN
  EXECUTE IMMEDIATE 'GRANT ROLE ram TO USER ' || CURRENT_USER();
  EXECUTE IMMEDIATE 'GRANT ROLE sham TO USER ' || CURRENT_USER();
END;


USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE LAB_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60;

GRANT USAGE ON WAREHOUSE LAB_WH TO ROLE RAM;
GRANT USAGE ON WAREHOUSE LAB_WH TO ROLE SHAM;

CREATE OR REPLACE DATABASE SECURITY_LAB_DB;

GRANT USAGE ON DATABASE SECURITY_LAB_DB TO ROLE RAM;
GRANT USAGE ON DATABASE SECURITY_LAB_DB TO ROLE SHAM;

CREATE OR REPLACE SCHEMA SECURITY_LAB_DB.STD_SCH;

GRANT USAGE ON SCHEMA SECURITY_LAB_DB.STD_SCH TO ROLE RAM;
GRANT USAGE ON SCHEMA SECURITY_LAB_DB.STD_SCH TO ROLE SHAM;

GRANT CREATE TABLE ON SCHEMA SECURITY_LAB_DB.STD_SCH TO ROLE RAM;

USE ROLE RAM;
USE WAREHOUSE LAB_WH;

CREATE OR REPLACE TABLE SECURITY_LAB_DB.STD_SCH.RAM_TABLE(ID INT,DATA STRING);
INSERT INTO security_lab_db.std_sch.ram_table VALUES (1, 'Standard Schema Data');

-- USE SECONDARY ROLES NONE;

SELECT * FROM SECURITY_LAB_DB.STD_SCH.RAM_TABLE;

GRANT SELECT ON TABLE SECURITY_LAB_DB.STD_SCH.RAM_TABLE TO ROLE SHAM;

USE ROLE SHAM;
SELECT * FROM SECURITY_LAB_DB.STD_SCH.RAM_TABLE;

