-- 1. Create Role and Virtual Warehouse
CREATE ROLE IF NOT EXISTS CORTEX_ANALYST_ROLE;
CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;

-- 2. Create Database and Schema for Metadata & Stage
CREATE DATABASE IF NOT EXISTS TPCH_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS TPCH_ANALYTICS.SEMANTIC_LAYER;

-- 3. Grant Privileges
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE CORTEX_ANALYST_ROLE;
GRANT ALL ON DATABASE TPCH_ANALYTICS TO ROLE CORTEX_ANALYST_ROLE;
GRANT ALL ON SCHEMA TPCH_ANALYTICS.SEMANTIC_LAYER TO ROLE CORTEX_ANALYST_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE CORTEX_ANALYST_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CORTEX_ANALYST_ROLE;
GRANT ROLE CORTEX_ANALYST_ROLE TO USER DATA2DOLLARS;
-- 4. Create Internal Stage for Semantic YAML Files
USE ROLE CORTEX_ANALYST_ROLE;
USE DATABASE TPCH_ANALYTICS;
USE SCHEMA SEMANTIC_LAYER;


CREATE OR REPLACE STAGE TPCH_MODEL_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');