-- 1. Create a dedicated sandbox environment
CREATE OR REPLACE DATABASE LINEAGE_DEMO_DB;
CREATE OR REPLACE SCHEMA LINEAGE_DEMO_SCHEMA;
USE SCHEMA LINEAGE_DEMO_DB.LINEAGE_DEMO_SCHEMA;

-- 2. Create Base Raw Table
CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    CREDIT_CARD VARCHAR
);

-- Insert sample records
INSERT INTO RAW_CUSTOMERS VALUES 
(101, 'Alex', 'Rider', 'alex@example.com', '4111-2222-3333-4444'),
(102, 'Sarah', 'Connor', 'sarah@example.com', '5500-0000-0000-0004');

-- 3. Data Movement: Create Processed Table (CTAS)
CREATE OR REPLACE TABLE PROCESSED_CUSTOMERS AS
SELECT 
    CUSTOMER_ID,
    UPPER(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS FULL_NAME,
    EMAIL
FROM RAW_CUSTOMERS;

-- 4. Object Dependency: Create downstream Analytics View
CREATE OR REPLACE VIEW VW_ACTIVE_CUSTOMERS AS
SELECT 
    CUSTOMER_ID, 
    FULL_NAME 
FROM PROCESSED_CUSTOMERS;
