-- CREATE OR REPLACE WAREHOUSE STANDARD_GEN2
-- WAREHOUSE_TYPE=STANDARD
-- WAREHOUSE_SIZE=MEDIUM
-- GENERATION='1'
-- MIN_CLUSTER_COUNT=1
-- MAX_CLUSTER_COUNT=3
-- SCALING_POLICY=STANDARD

-- AUTO_SUSPEND=60
-- AUTO_RESUME=TRUE
-- INITIALLY_SUSPENDED =TRUE
-- MAX_CONCURRENCY_LEVEL = 8 

-- STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 300
-- STATEMENT_TIMEOUT_IN_SECONDS = 1800  -- fORCE STOP QUERIES EXCEEDING 30 MIN RUNTIME


-- COMMENT = 'HIGHLY RECOMMEND';


-- sELECT * FROM RETAIL_DB.RAW.API_ORDERS;

ALTER WAREHOUSE COMPUTE_WH SUSPEND;



SHOW WAREHOUSES LIKE 'COMPUTE_WH';


CREATE OR REPLACE ROLE demo_viewer_role;

GRANT USAGE ON DATABASE demo_db TO ROLE demo_viewer_role;
GRANT SELECT ON TABLE demo_table_clone TO ROLE demo_viewer_role;

-- UNDROP TABLE demo_table_clone;

-- CREATE OR REPLACE TABLE demo_table_clone 
-- CLONE final_score_table;

-- ALTER TABLE demo_table_two RENAME TO final_score_table;

-- SELECT COUNT(*) FROM final_score_table;

-- SHOW TABLES  LIKE 'final_score_table';

-- DESCRIBE TABLE final_score_table;
--CREATE OR REPLACE TABLE demo_table_two (id INT, score INT);
